version: '3'

networks:
  backend:
    driver: bridge

services:

  server:
    build:
      context: ./etc/apache2
      args:
        USER_ID: ${USER_ID:?err}
        GROUP_ID: ${GROUP_ID:?err}
    volumes:
      - ./etc/apache2/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./etc/apache2/vhosts.conf:/usr/local/apache2/conf/extra/vhosts.conf
      - .:/var/www/html
      - ${LOG_PATH}/server:/usr/local/apache2/logs
    ports:
      - "${SERVER_HTTP_PORT}:80"
      - "${SERVER_HTTPS_PORT}:443"
    networks:
      - backend

  app:
    build:
      context: ./etc/php7.4
      args:
        USER_ID: ${USER_ID:?err}
        GROUP_ID: ${GROUP_ID:?err}
    volumes:
      - .:/var/www/html
      - ./etc/php7.4/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ~/.ssh:/home/www-data/.ssh
      - ~/.composer:/home/www-data/.composer
      - ~/.gitconfig:/home/www-data/.gitconfig
      - ~/.ash_history:/home/www-data/.ash_history
    environment:
      - XDEBUG_CONFIG=client_host=${DOCKER_GATEWAY_HOST:-host.docker.internal}
      - PHP_IDE_CONFIG=serverName=gamefinder
    networks:
      - backend
